# syntax=docker/dockerfile:1

# ---- Base ----
ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim AS base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    pipx \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:$PATH"
# ENV PATH /usr/local/bin:$PATH

# RUN pipx ensurepath

ENV POETRY_VERSION=2.2.1 \
    POETRY_NO_INTERACTION=1 
    # POETRY_VIRTUALENVS_IN_PROJECT=false

# Install Poetry via pipx
RUN pipx install "poetry==$POETRY_VERSION"


# ---- builder ----
FROM base AS builder

WORKDIR /app

# Copy project metadata first (leverages Docker layer caching)
COPY pyproject.toml poetry.lock ./


RUN poetry install --no-root --only main


# Copy the actual application code
COPY /app /db /tests/ ./


# ---- Final Image ----
FROM python:${PYTHON_VERSION}-slim AS final

# Create non-root user
RUN useradd -m -u 1000 appuser

WORKDIR /app

# Copy the runtime environment from builder
COPY --from=builder /app /app

USER appuser

# Expose FastAPI port
EXPOSE 8000

# Start the app (FastAPI example)
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD [ "fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000" ]
ENTRYPOINT ["/bin/bash", "-c", "echo 'hello'; sleep infinity"]
